name: manyfold
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy==1.19.5
  - pandas==1.2.5
  - six==1.15.0
  - pip=21.0.1
  - jupyter
  - pip:
      - --find-links https://storage.googleapis.com/jax-releases/libtpu_releases.html
      - jax[tpu]==0.3.14
      - jaxlib==0.3.14
      - absl-py==0.13.0
      - biopython==1.79
      - chex>=0.0.7
      - dm-haiku==0.0.5
      - dm-tree==0.1.6
      - jmp==0.0.2
      - google-cloud-storage==1.42.0
      - hydra-core==1.2.0
      - immutabledict==2.0.0
      - matplotlib==3.5.2
      - ml-collections==0.1.0
      - mock==4.*
      - numpy==1.19.5
      - omegaconf==2.2.1
      - optax==0.0.9
      - psutil==5.8.0
      - regex==2022.1.18
      - scipy==1.7.0
      - tensorflow-cpu==2.5.0
